package client;

import javax.swing.*;

public class Client {
    private JTabbedPane Wines;
    private JPanel panel1;
    private JButton connectToServerButton;
    private JButton editButton;
    private JButton printButton;
    private JButton deleteButton;
    private JButton addButton;
    private JButton getTableButton;
    private JTable Winestable1;
    private JButton GetTableCustomers;
    private JButton DeleteCustomers;
    private JButton EditCustomers;
    private JButton PrintCustomers;
    private JTable Customertable;
    private JTable Reviewstable;
    private JButton GetTablleReviews;
    private JButton AddReviews;
    private JButton EditReviews;
    private JButton DeleteReviews;
    private JButton PrintReviews;
    private JTextField TitleWinestextfield;
    private JTextField WineIdTextfield;
    private JTextField DesignationWinesTextfield;
    private JTextField ProvinceWinesTextfield;
    private JTextField TastertwitterHandleWinesTextfiled;
    private JTextField VarietyWinesTextfield;
    private JTextField WineryTextfield;
    private JTextField YearWinesTextfield;
    private JTextField CustomerIdCustomersTextfield;
    private JTextField FirstnameCustomersTextfield;
    private JTextField LastnameCustomersTextfield;
    private JTextField AddressCustomersTextfield;
    private JTextField CityCustomersTextfield;
    private JTextField CountryCustomersTextfield;
    private JTextField PostalTextfield;
    private JTextField Phone1CustomersTextfield;
    private JTextField Phone2CustomersTextfield;
    private JTextField EmailCustomersTextfield;
    private JTextField ReviewIdReviwsTextfield;
    private JTextField CustomerIDReviewsTextfield;
    private JTextField WineIdReviewsTexfield;
    private JTextField CustomerDescripReviewsTextfield;
    private JTextField CustomerRatingReviewsTextfield;
    private JTextField DateAddedReviewTextfield;
    private JLabel WineIDLabel;
    private JLabel CountryWinesLabel;
    private JLabel DesignationLabel;
    private JLabel DescriptionLabel;
    private JLabel PointsLabel;
    private JLabel PriceLabel;
    private JLabel ProvinceLabel;
    private JLabel Region1Label;
    private JLabel Region2Label;
    private JLabel TasterNameLabel;
    private JLabel TasterTwitterHandleLabel;
    private JLabel TitleLabel;
    private JLabel VarietyLabel;
    private JLabel WineryLabel;
    private JLabel YearLabel;
    private JTextField CountryWinesTextfield;
    private JTextField DescriptionWinesTextfield;
    private JTextField PointsWinesTextfield;
    private JTextField PriceWinesTextfield;
    private JTextField Region1WinesTextfield;
    private JTextField Region2WinestTextfield;
    private JTextField TasterNameWinestextfield;
    private JLabel CustomerIDLabel;
    private JLabel FirstnameLabel;
    private JLabel LastNameLabel;
    private JLabel AddressLabel;
    private JLabel Countrylabel;
    private JLabel PostalLabel;
    private JLabel Phone1Label;
    private JLabel Phone2Label;
    private JLabel ReviewIdLabel;
    private JLabel CustomerIdLabel;
    private JLabel WineIdLabel;
    private JLabel CustomerDescriptionReviewsLabel;
    private JLabel CustomerratingReviewsLabel;
    private JLabel DateaddedLabel;


}
